# Konfigurasi User Lab (Non-root)

USERNAME=labuser
SHELL=/bin/bash
HOME=/home/labuser

# Tidak dimasukkan ke grup sudo
GROUPS=audio,video,plugdev,netdev

# Pembatasan hak akses
DISABLE_ROOT_LOGIN=true
PASSWORD_POLICY=strong
AUTO_LOGIN=true

# Catatan:
# User ini tidak memiliki hak administratif
# Cocok untuk penggunaan bersama di laboratorium
