# Kernel parameter tuning for Academic / Lab Linux Distro

# Proteksi terhadap IP spoofing
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Menonaktifkan ICMP redirect (keamanan)
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0

# Proteksi terhadap SYN flood attack
net.ipv4.tcp_syncookies = 1

# Membatasi core dump (keamanan)
fs.suid_dumpable = 0

# Meningkatkan performa I/O ringan (lab usage)
vm.swappiness = 10
